# Generated by Django 6.0.3 on 2026-04-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='driver_license_document',
            field=models.FileField(blank=True, null=True, upload_to='carrier_docs/personal/'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='id_card_document',
            field=models.FileField(blank=True, null=True, upload_to='carrier_docs/personal/'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='other_personal_document',
            field=models.FileField(blank=True, null=True, upload_to='carrier_docs/personal/'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='vehicle_insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='carrier_docs/vehicle/'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='vehicle_registration_document',
            field=models.FileField(blank=True, null=True, upload_to='carrier_docs/vehicle/'),
        ),
    ]
